
import React, { createContext, useContext, useState, useEffect } from 'react';
import { useUser } from './UserContext';

type Language = 'en' | 'en-gb' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'ar' | 'pt' | 'ru';

interface LanguageContextType {
    language: Language;
    t: (key: string) => string;
    setLanguage: (lang: Language) => void;
}

const dictionaries: Record<string, Record<string, string>> = {
    en: {
        'dashboard.hello': 'Hello',
        'dashboard.ready': 'Ready to make some noise? You\'re doing great.',
        'dashboard.activeProjects': 'Active Projects',
        'dashboard.studioTools': 'Studio Tools',
        'dashboard.dowdBucks': 'DowdBucks',
        'dashboard.level': 'Level',
        'dashboard.xp': 'XP',
        'dashboard.totalXp': 'Total Experience',
        'dashboard.nextLevel': 'XP to Next Level',
        'dashboard.continue': 'Continue Project',
        'calendar.thisWeek': 'This Week',
        'calendar.upcoming': 'Upcoming Events',
        'calendar.today': 'Today',
        'calendar.noEvents': 'No upcoming events',
        'sidebar.dashboard': 'Dashboard',
        'sidebar.learning': 'Learning',
        'sidebar.projects': 'Projects',
        'sidebar.resources': 'Resources',
        'sidebar.store': 'Store',
        'sidebar.inventory': 'Inventory',
        'sidebar.grades': 'Grades',
        'sidebar.profile': 'Profile',
        'sidebar.calendar': 'Calendar',
        'sidebar.support': 'Support',
        'sidebar.logout': 'Logout',
        'learning.cohort': 'Cohort',
        'project.notFound': 'Project not found',
        'project.back': 'Back to Dashboard',
        'project.scenario': 'Project Scenario',
        'project.tasks': 'Submission Tasks',
        'project.outcomes': 'Learning Outcomes',
        'project.resources': 'Essential Resources',
        'project.status.notStarted': 'Not Started',
        'project.status.graded': 'Graded',
        'project.status.pending': 'Pending Mark',
        'project.status.inProgress': 'In Progress',
        'project.start': 'Start',
        'project.view': 'View',
        'project.criteria': 'Criteria',
        'task.notFound': 'Task or Project not found',
        'task.back': 'Back to Project',
        'task.criteria': 'Criteria',
        'task.description': 'Task Description',
        'task.reward': 'XP Reward',
        'task.deadline': 'Deadline',
        'task.completed': 'Task Completed',
        'task.verified': 'This task has been verified as complete by your teacher.',
        'task.gradeAwarded': 'Grade Awarded',
        'task.submissionDisabled': 'Submission Disabled',
        'task.manualVerificationOnly': 'To complete this task, please demonstrate your work to your teacher during class. They will verify your progress and mark this task as complete manually.',
        'task.actionRequired': 'Action Required:',
        'task.action.prepare': 'Prepare your evidence (files, performance, etc.)',
        'task.action.show': 'Show your work to your tutor',
        'task.action.ask': 'Ask them to "Mark as Complete"',
        'store.title': 'DowdBucks Store',
        'store.subtitle': 'Spend your hard-earned rewards on exclusive flair',
        'store.owned': 'Owned',
        'store.processing': 'Processing...',
        'store.buy': 'Buy',
        'store.insufficient': 'Insufficient DowdBucks!',
        'store.comingSoon': 'More coming soon',
        'inventory.title': 'My Inventory',
        'inventory.subtitle': 'Your purchased items and rewards',
        'inventory.noItems': 'No items yet',
        'inventory.visitStore': 'Visit the DowdBucks Store to purchase exclusive items!',
        'inventory.equip': 'Equip',
        'inventory.unequip': 'Unequip',
        'inventory.active': 'Active',
        'inventory.boostActivated': 'Boost activated! You now have 2x XP for 7 days!',
        'inventory.stats': 'Collection Stats',
        'inventory.itemsOwned': 'Items Owned',
        'inventory.collectionComplete': 'Collection Complete',
        'inventory.balance': 'Current Balance',
        'item.darkMode': 'Dark Mode Pro',
        'item.darkModeDesc': 'Exclusive high-contrast theme variant',
        'item.goldBorder': 'Gold Avatar Border',
        'item.goldBorderDesc': 'Shine in the leaderboards',
        'item.customAccent': 'Custom Accent Pack',
        'item.customAccentDesc': 'Change UI accent to your choice',
        'item.badgeFlare': 'Badge Flare',
        'item.badgeFlareDesc': 'Add sparkle to your status badges',
        'projects.title': 'My Projects',
        'projects.subtitle': 'Coursework allocated to',
        'projects.noDeadline': 'No Deadline',
        'projects.completion': 'Completion',
        'projects.tasksDone': 'Tasks Done',
        'projects.viewDetails': 'View Details',
        'projects.noProjects': 'No Projects Allocated',
        'projects.contactTeacher': 'Contact your teacher if you believe this is an error.',
        'grades.title': 'Grades & Progress',
        'grades.matrix': 'Assessment Matrix',
        'grades.tracking': 'Tracking against UAL criteria...',
        'booking.title': 'Studio & Equipment',
        'booking.subtitle': 'Manage studio time and equipment loans',
        'booking.addStudio': 'Add Studio',
        'booking.addItem': 'Add Item',
        'booking.tab.studio': 'Studio Booking',
        'booking.tab.equipment': 'Equipment Loans',
        'booking.availableStudios': 'Available Studios',
        'booking.capacity': 'Capacity',
        'booking.people': 'people',
        'booking.equipment': 'Equipment',
        'booking.manageSchedule': 'Manage Schedule',
        'booking.bookNow': 'Book Now',
        'booking.requests': 'Booking Requests',
        'booking.myBookings': 'My Bookings',
        'booking.unknownStudio': 'Unknown Studio',
        'booking.by': 'by',
        'booking.purpose': 'Purpose',
        'booking.reject': 'Reject',
        'booking.approve': 'Approve',
        'booking.cancel': 'Cancel',
        'booking.noBookings': 'No bookings found.',
        'booking.availableEquipment': 'Available Equipment',
        'booking.stock': 'Stock',
        'booking.editItem': 'Edit Item',
        'booking.requestLoan': 'Request Loan',
        'booking.outOfStock': 'Out of Stock',
        'booking.loanRequests': 'Loan Requests & Active Loans',
        'booking.myLoans': 'My Loans',
        'booking.unknownItem': 'Unknown Item',
        'booking.due': 'Due',
        'booking.requestedBy': 'Requested by',
        'booking.markReturned': 'Mark Returned',
        'booking.noLoans': 'No loans found.',
        'booking.modal.addStudio': 'Add New Studio',
        'booking.modal.addEquipment': 'Add New Equipment',
        'booking.modal.book': 'Book',
        'booking.modal.request': 'Request',
        'booking.modal.edit': 'Edit',
        'booking.label.name': 'Name',
        'booking.label.capacity': 'Capacity',
        'booking.label.list': 'Equipment List (comma separated)',
        'booking.label.category': 'Category',
        'booking.label.quantity': 'Total Quantity',
        'booking.label.date': 'Date',
        'booking.label.time': 'Time',
        'booking.label.duration': 'Duration (Hours)',
        'booking.label.returnDate': 'Return Date',
        'booking.label.loanQty': 'Quantity',
        'booking.alert.stock': 'Not enough stock available!',
        'booking.alert.reduce': 'Cannot reduce total quantity below currently loaned amount.',
        'booking.info.max': 'Max available',
        'booking.info.current': 'Currently Available',
        'booking.cat.mic': 'Microphone',
        'booking.cat.inst': 'Instrument',
        'booking.cat.cable': 'Cable',
        'booking.cat.interface': 'Interface',
        'booking.cat.other': 'Other',
        'profile.title': 'My Account',
        'profile.subtitle': 'Manage your profile settings and preferences',
        'profile.toggleTheme': 'Toggle Theme',
        'profile.theme': 'Theme',
        'profile.changeAvatar': 'Change Avatar',
        'profile.appearance': 'Appearance',
        'profile.accessibility': 'Accessibility',
        'profile.fontSize': 'Font Size',
        'profile.colorProfile': 'Color Profile',
        'profile.cp.standard': 'Standard',
        'profile.cp.protanopia': 'Red-Blind (Protanopia)',
        'profile.cp.deuteranopia': 'Green-Blind (Deuteranopia)',
        'profile.cp.tritanopia': 'Blue-Blind (Tritanopia)',
        'profile.personalInfo': 'Personal Information',
        'profile.fullName': 'Full Name',
        'profile.username': 'Username',
        'profile.cohort': 'Cohort',
        'profile.department': 'Department',
        'profile.officeRoom': 'Office Room',
        'profile.accountSettings': 'Account Settings',
        'profile.notifications': 'Notifications',
        'profile.inAppEnabled': 'In-app enabled',
        'profile.configure': 'Configure',
        'profile.language': 'Language',
        'profile.chooseAvatar': 'Choose Your Avatar',
        'profile.avatar.cat': 'Cat',
        'profile.avatar.dog': 'Dog',
        'profile.avatar.duck': 'Duck',
        'profile.avatar.frog': 'Frog',
        'profile.avatar.llama': 'Llama',
        'profile.avatar.octopus': 'Octopus',
        'profile.avatar.panda': 'Panda',
        'profile.avatar.parrot': 'Parrot',
        'profile.avatar.penguin': 'Penguin',
        'profile.theme.light': 'Light',
        'profile.theme.dark': 'Dark',
        'profile.theme.contrast': 'Contrast',
        'teacher.dashboard.title': 'Teacher Dashboard',
        'teacher.dashboard.subtitle': 'Welcome back. Here is your academic overview.',
        'teacher.dashboard.newProject': 'New Project',
        'teacher.dashboard.activeStudents': 'Active Students',
        'teacher.dashboard.enrolledCohorts': 'Enrolled across cohorts',
        'teacher.dashboard.activeProjects': 'Active Projects',
        'teacher.dashboard.publishedLive': 'Published & Live',
        'teacher.dashboard.needsMarking': 'Needs Marking',
        'teacher.dashboard.submissionsReview': 'Submissions awaiting review',
        'teacher.dashboard.qa.manageStudents': 'Manage Students',
        'teacher.dashboard.qa.viewProfiles': 'View & Edit Profiles',
        'teacher.dashboard.qa.curriculum': 'Curriculum',
        'teacher.dashboard.qa.manageProjects': 'Manage Projects',
        'teacher.dashboard.qa.assessmentHub': 'Assessment Hub',
        'teacher.dashboard.qa.pending': 'Pending',
        'teacher.dashboard.qa.courses': 'Courses',
        'teacher.dashboard.qa.manageContent': 'Manage Content',
        'teacher.dashboard.qa.academicConfig': 'Academic Config',
        'teacher.dashboard.quickActions': 'Quick Actions',
        'teacher.dashboard.termProgress': 'Term Progress',
        'teacher.dashboard.markingBacklog': 'Marking Backlog',
        'teacher.dashboard.backlogMessage': 'You have high volume of unmarked work.',
        'teacher.dashboard.goToGrading': 'Go to Grading',
        'teacher.students.title': 'Manage Students',
        'teacher.students.subtitle': 'Overview of all student cohorts and performance',
        'teacher.students.addStudent': 'Add Student',
        'teacher.students.totalStudents': 'Total Students',
        'teacher.students.active': 'Active',
        'teacher.students.atRisk': 'At Risk',
        'teacher.students.searchPlaceholder': 'Search by name or username...',
        'teacher.students.allCohorts': 'All Cohorts',
        'teacher.students.level2': 'Level 2',
        'teacher.students.level3a': 'Level 3A (Year 1)',
        'teacher.students.level3b': 'Level 3B (Year 2)',
        'teacher.students.table.name': 'Name',
        'teacher.students.table.cohort': 'Cohort',
        'teacher.students.table.status': 'Status',
        'teacher.students.table.actions': 'Actions',
        'teacher.students.actions.placeholder': 'Actions...',
        'teacher.students.actions.edit': 'Edit Details',
        'teacher.students.actions.viewCreds': 'View Credentials',
        'teacher.students.actions.resetPass': 'Reset Password',
        'teacher.students.actions.delete': 'Delete Student',
        'teacher.students.noStudents': 'No students found matching your filters.',
        'teacher.students.modal.edit': 'Edit Student',
        'teacher.students.modal.add': 'Add New Student',
        'teacher.students.modal.name': 'Student Name',
        'teacher.students.modal.namePlaceholder': 'e.g. John Doe',
        'teacher.students.modal.cohort': 'Cohort',
        'teacher.students.modal.credentials': 'Credentials',
        'teacher.students.modal.username': 'Username',
        'teacher.students.modal.usernamePlaceholder': 'auto.generated',
        'teacher.students.modal.password': 'Password',
        'teacher.students.modal.passwordPlaceholder': 'Password',
        'teacher.students.modal.cancel': 'Cancel',
        'teacher.students.modal.update': 'Update Student',
        'teacher.students.modal.create': 'Create Student',
        'teacher.students.alert.fillAll': 'Please fill in all fields',
        'teacher.students.alert.updated': 'Updated Student:',
        'teacher.students.alert.created': 'Created Student:',
        'teacher.students.alert.username': 'Username:',
        'teacher.students.alert.password': 'Password:',
        'teacher.students.alert.resetConfirm': 'Reset password for',
        'teacher.students.alert.resetSuccess': 'Password reset to:',
        'teacher.students.alert.deleteConfirm': 'Are you sure you want to delete {name}? This cannot be undone.',
        'teacher.projects.title': 'Project Management',
        'teacher.projects.subtitle': 'Oversee, track, and manage all published coursework',
        'teacher.projects.newIngestion': 'New Project Ingestion',
        'teacher.projects.searchPlaceholder': 'Search projects or units...',
        'teacher.projects.studentsTracking': 'Students Tracking',
        'teacher.projects.completionRate': 'Completion Rate',
        'teacher.projects.tasksCount': 'Tasks: {count}',
        'teacher.projects.editProject': 'Edit Project',
        'teacher.projects.cohort': 'Cohort',
        'teacher.projects.noProjects': 'No projects found',
        'teacher.projects.noProjectsDesc': 'Try adjusting your filters or ingest a new project brief.',
        'teacher.projects.deleteConfirm': 'Are you sure you want to delete "{title}"? This cannot be undone.',
        'teacher.projects.overlay.settings': 'Project Settings',
        'teacher.projects.overlay.tasks': 'Tasks ({count})',
        'teacher.projects.overlay.title': 'Project Title',
        'teacher.projects.overlay.unit': 'Unit / Qualification',
        'teacher.projects.overlay.targetCohort': 'Target Cohort',
        'teacher.projects.overlay.deadline': 'Project Deadline',
        'teacher.projects.overlay.gradingScheme': 'Grading Scheme',
        'teacher.projects.overlay.xpReward': 'Completion XP Reward',
        'teacher.projects.overlay.dowdBucks': 'Completion DowdBucks',
        'teacher.projects.overlay.taskTitle': 'Task Title',
        'teacher.projects.overlay.description': 'Description',
        'teacher.projects.overlay.evidenceTypes': 'Allowed Evidence Types (Select all that apply)',
        'teacher.projects.overlay.criteria': 'Criteria References',
        'teacher.projects.overlay.addTask': 'Add Task',
        'teacher.projects.overlay.save': 'Save Changes',
        'teacher.projects.overlay.cancel': 'Cancel',
        'teacher.projects.overlay.done': 'Done',
        'teacher.projects.overlay.removeTaskConfirm': 'Are you sure you want to remove this task?',
        'teacher.projects.tracker.tracking': 'Tracking {count} Students',
        'teacher.projects.tracker.search': 'Search students...',
        'teacher.projects.tracker.status': 'Task Completion Status',
        'teacher.projects.tracker.note': 'Note',
        'teacher.projects.tracker.addNote': 'Add Note',
        'teacher.projects.tracker.completed': 'COMPLETED',
        'teacher.projects.tracker.undo': 'Undo Verification',
        'teacher.projects.tracker.verify': 'Verify Submission',
        'teacher.projects.tracker.markComplete': 'Mark Complete',
        'teacher.projects.tracker.enterNotes': 'Enter notes for this task...',
        'teacher.projects.tracker.saveNote': 'Save Note',
        'teacher.projects.tracker.selectStudent': 'Select a student from the list to view their progress.',
        'teacher.projects.tracker.uncheckConfirm': 'Are you sure you want to uncheck this task? XP will be deducted.',
        'teacher.projects.evidence.audio': 'Audio File',
        'teacher.projects.evidence.video': 'Video File',
        'teacher.projects.evidence.google': 'Google App',
        'teacher.projects.evidence.url': 'External URL',
        'teacher.quizzes.title': 'Content Management',
        'teacher.quizzes.subtitle': 'Manage your courses, lessons, and quizzes',
        'teacher.quizzes.newCourse': 'New Course',
        'teacher.quizzes.courseDesc': 'Course description...',
        'teacher.quizzes.deleteConfirm': 'Delete this course? All content inside will be moved to "Uncategorized".',
        'teacher.quizzes.enterTopic': 'Enter a topic for the quiz:',
        'teacher.quizzes.generateFail': 'Failed to generate quiz.',
        'teacher.quizzes.newQuiz': 'New Quiz',
        'teacher.quizzes.quizDesc': 'Quiz description...',
        'teacher.quizzes.newQuestion': 'New Question',
        'teacher.quizzes.option': 'Option {number}',
        'teacher.quizzes.newLesson': 'New Lesson',
        'teacher.quizzes.lessonDesc': 'Short description of the lesson...',
        'teacher.quizzes.lessonContent': '# Lesson Title\n\nEnter your lesson content here. Supports Markdown.',
        'teacher.quizzes.editCourse': 'Edit Course',
        'teacher.quizzes.createCourse': 'Create Course',
        'teacher.quizzes.field.title': 'Title',
        'teacher.quizzes.field.description': 'Description',
        'teacher.quizzes.field.color': 'Color Theme',
        'teacher.quizzes.field.xp': 'XP Reward',
        'teacher.quizzes.field.content': 'Content (Markdown)',
        'teacher.quizzes.field.status': 'Status',
        'teacher.quizzes.field.questionType': 'Question Type',
        'teacher.quizzes.saveCourse': 'Save Course',
        'teacher.quizzes.saveLesson': 'Save Lesson',
        'teacher.quizzes.saveQuiz': 'Save Quiz',
        'teacher.quizzes.cancel': 'Cancel',
        'teacher.quizzes.settings': 'Settings',
        'teacher.quizzes.draft': 'Draft',
        'teacher.quizzes.published': 'Published',
        'teacher.quizzes.questions': 'Questions ({count})',
        'teacher.quizzes.question': 'Question {number}',
        'teacher.quizzes.enterQuestion': 'Enter question text...',
        'teacher.quizzes.type.mc': 'Multiple Choice',
        'teacher.quizzes.type.listening': 'Listening (Interval)',
        'teacher.quizzes.type.instrument': 'Instrument (Fretboard)',
        'teacher.quizzes.addOption': '+ Add Option',
        'teacher.quizzes.addQuestion': 'Add Question',
        'teacher.quizzes.backToCourses': 'Back to Courses',
        'teacher.quizzes.aiGenerate': 'AI Generate',
        'teacher.quizzes.addLesson': 'Add Lesson',
        'teacher.quizzes.createQuiz': 'Create Quiz',
        'teacher.quizzes.noContent': 'No content in this course yet.',
        'teacher.quizzes.uncategorized': 'Uncategorized',
        'teacher.quizzes.uncategorizedDesc': 'Quizzes not in any course',
        'teacher.quizzes.quizCount': '{count} Quizzes',
        'teacher.quizzes.lessonCount': '{count} Lessons',
        'teacher.ingestion.title': 'Curriculum Ingestion',
        'teacher.ingestion.subtitle': 'Convert PDF project briefs into structured coursework',
        'teacher.ingestion.publishConfirm': 'Are you sure you want to Finalize & Publish this project?\n\nIt will become immediately visible to students in the {cohort} cohort.',
        'teacher.ingestion.selected': 'selected',
        'teacher.ingestion.untitled': 'Untitled Project',
        'teacher.ingestion.unknownUnit': 'Unknown Unit',
        'teacher.ingestion.finalize': 'Finalize & Publish',
        'teacher.ingestion.reviewRequired': 'Review Required',
        'teacher.ingestion.reviewDesc': 'Please verify all extracted data below. Ensure Project Number and Name (* marked) are correct before publishing.',
        'teacher.ingestion.processing': 'Processing Brief...',
        'teacher.ingestion.upload': 'Upload Project Brief',
        'teacher.ingestion.uploadDesc': 'Select a PDF file to automatically extract tasks, deadlines, and units.',
        'teacher.ingestion.projectDetails': 'Project Details',
        'teacher.ingestion.projectTitle': 'Project Title',
        'teacher.ingestion.targetCohort': 'Target Cohort',
        'teacher.ingestion.unitsCovered': 'Units Covered',
        'teacher.ingestion.deadline': 'Project Deadline',
        'teacher.ingestion.gradingScheme': 'Grading Scheme',
        'teacher.ingestion.tasks': 'Project Tasks ({count})',
        'teacher.ingestion.addTask': 'Add Task',
        'teacher.ingestion.newTask': 'New Task',
        'teacher.ingestion.taskDesc': 'Enter task description...',
        'teacher.ingestion.taskTitle': 'Task Title',
        'teacher.ingestion.description': 'Description',
        'teacher.ingestion.evidenceTypes': 'Required Evidence Types (Select all that apply)',
        'teacher.ingestion.audio': 'Audio File',
        'teacher.ingestion.video': 'Video File',
        'teacher.ingestion.google': 'Google App',
        'teacher.ingestion.url': 'External URL',
        'teacher.ingestion.dueDate': 'Due Date',
        'teacher.ingestion.xpReward': 'XP Reward',
        'teacher.ingestion.criteria': 'Criteria (comma separated)',
        'teacher.ingestion.parseError': 'Failed to parse PDF: {error}\n\nPlease ensure it is a valid project brief.',
        'teacher.assessment.title': 'Assessment Hub',
        'teacher.assessment.subtitle': 'Manage and grade student submissions',
        'teacher.assessment.verify': 'Verify Student Work',
        'teacher.assessment.stat.pending': 'Pending',
        'teacher.assessment.stat.late': 'Late',
        'teacher.assessment.stat.completed': 'Completed Today',
        'teacher.assessment.filter': 'Filter:',
        'teacher.assessment.filter.all': 'All',
        'teacher.assessment.filter.pending': 'Pending Mark',
        'teacher.assessment.filter.late': 'Late',
        'teacher.assessment.filter.graded': 'Graded',
        'teacher.assessment.search': 'Search students or tasks...',
        'teacher.assessment.viewGrade': 'View Grade',
        'teacher.assessment.grade': 'Grade Submission',
        'teacher.assessment.noSubmissions': 'No submissions found for the selected filter.',
    },
    'en-gb': {
        'dashboard.hello': 'Hello',
        'dashboard.ready': 'Ready to make some noise? You\'re doing great.',
        'dashboard.activeProjects': 'Active Projects',
        'dashboard.studioTools': 'Studio Tools',
        'dashboard.dowdBucks': 'DowdBucks',
        'dashboard.level': 'Level',
        'dashboard.xp': 'XP',
        'dashboard.totalXp': 'Total Experience',
        'dashboard.nextLevel': 'XP to Next Level',
        'dashboard.continue': 'Continue Project',
        'calendar.thisWeek': 'This Week',
        'calendar.upcoming': 'Upcoming Events',
        'calendar.today': 'Today',
        'calendar.noEvents': 'No upcoming events',
        'sidebar.dashboard': 'Dashboard',
        'sidebar.learning': 'Learning',
        'sidebar.projects': 'Projects',
        'sidebar.resources': 'Resources', // "Centre" could be used if appropriate, keeping Resources for now
        'sidebar.store': 'Store',
        'sidebar.inventory': 'Inventory',
        'sidebar.grades': 'Grades', // "Marks" is common in UK, but Grades is also used. Keeping Grades for now.
        'sidebar.profile': 'Profile',
        'sidebar.calendar': 'Calendar',
        'sidebar.support': 'Support',
        'sidebar.logout': 'Log Out',
        'learning.title': 'My Learning Path',
        'learning.subtitle': 'Track your progress and access your course materials',
        'learning.currentConfig': 'Current Configuration',
        'learning.year': 'Year',
        'learning.level': 'Level',
        'learning.cohort': 'Cohort',

        'project.notFound': 'Project not found',
        'project.back': 'Back to Dashboard',
        'project.scenario': 'Project Scenario',
        'project.tasks': 'Submission Tasks',
        'project.outcomes': 'Learning Outcomes',
        'project.resources': 'Essential Resources',
        'project.status.notStarted': 'Not Started',
        'project.status.graded': 'Graded',
        'project.status.pending': 'Pending Mark',
        'project.status.inProgress': 'In Progress',
        'project.start': 'Start',
        'project.view': 'View',
        'project.criteria': 'Criteria',
        'task.notFound': 'Task or Project not found',
        'task.back': 'Back to Project',
        'task.criteria': 'Criteria',
        'task.description': 'Task Description',
        'task.reward': 'XP Reward',
        'task.deadline': 'Deadline',
        'task.completed': 'Task Completed',
        'task.verified': 'This task has been verified as complete by your teacher.',
        'task.gradeAwarded': 'Grade Awarded',
        'task.submissionDisabled': 'Submission Disabled',
        'task.manualVerificationOnly': 'To complete this task, please demonstrate your work to your teacher during class. They will verify your progress and mark this task as complete manually.',
        'task.actionRequired': 'Action Required:',
        'task.action.prepare': 'Prepare your evidence (files, performance, etc.)',
        'task.action.show': 'Show your work to your tutor',
        'task.action.ask': 'Ask them to "Mark as Complete"',
        'store.title': 'DowdBucks Store',
        'store.subtitle': 'Spend your hard-earned rewards on exclusive flair',
        'store.owned': 'Owned',
        'store.processing': 'Processing...',
        'store.buy': 'Buy',
        'store.insufficient': 'Insufficient DowdBucks!',
        'store.comingSoon': 'More coming soon',
        'inventory.title': 'My Inventory',
        'inventory.subtitle': 'Your purchased items and rewards',
        'inventory.noItems': 'No items yet',
        'inventory.visitStore': 'Visit the DowdBucks Store to purchase exclusive items!',
        'inventory.equip': 'Equip',
        'inventory.unequip': 'Unequip',
        'inventory.active': 'Active',
        'inventory.boostActivated': 'Boost activated! You now have 2x XP for 7 days!',
        'inventory.stats': 'Collection Stats',
        'inventory.itemsOwned': 'Items Owned',
        'inventory.collectionComplete': 'Collection Complete',
        'inventory.balance': 'Current Balance',
        'item.darkMode': 'Dark Mode Pro',
        'item.darkModeDesc': 'Exclusive high-contrast theme variant',
        'item.goldBorder': 'Gold Avatar Border',
        'item.goldBorderDesc': 'Shine in the leaderboards',
        'item.customAccent': 'Custom Accent Pack',
        'item.customAccentDesc': 'Change UI accent to your choice',
        'item.badgeFlare': 'Badge Flare',
        'item.badgeFlareDesc': 'Add sparkle to your status badges',
        'projects.title': 'My Projects',
        'projects.subtitle': 'Coursework allocated to',
        'projects.noDeadline': 'No Deadline',
        'projects.completion': 'Completion',
        'projects.tasksDone': 'Tasks Done',
        'projects.viewDetails': 'View Details',
        'projects.noProjects': 'No Projects Allocated',
        'projects.contactTeacher': 'Contact your teacher if you believe this is an error.',
        'grades.title': 'Grades & Progress',
        'grades.matrix': 'Assessment Matrix',
        'grades.tracking': 'Tracking against UAL criteria...',
        'booking.title': 'Studio & Equipment',
        'booking.subtitle': 'Manage studio time and equipment loans',
        'booking.addStudio': 'Add Studio',
        'booking.addItem': 'Add Item',
        'booking.tab.studio': 'Studio Booking',
        'booking.tab.equipment': 'Equipment Loans',
        'booking.availableStudios': 'Available Studios',
        'booking.capacity': 'Capacity',
        'booking.people': 'people',
        'booking.equipment': 'Equipment',
        'booking.manageSchedule': 'Manage Schedule',
        'booking.bookNow': 'Book Now',
        'booking.requests': 'Booking Requests',
        'booking.myBookings': 'My Bookings',
        'booking.unknownStudio': 'Unknown Studio',
        'booking.by': 'by',
        'booking.purpose': 'Purpose',
        'booking.reject': 'Reject',
        'booking.approve': 'Approve',
        'booking.cancel': 'Cancel',
        'booking.noBookings': 'No bookings found.',
        'booking.availableEquipment': 'Available Equipment',
        'booking.stock': 'Stock',
        'booking.editItem': 'Edit Item',
        'booking.requestLoan': 'Request Loan',
        'booking.outOfStock': 'Out of Stock',
        'booking.loanRequests': 'Loan Requests & Active Loans',
        'booking.myLoans': 'My Loans',
        'booking.unknownItem': 'Unknown Item',
        'booking.due': 'Due',
        'booking.requestedBy': 'Requested by',
        'booking.markReturned': 'Mark Returned',
        'booking.noLoans': 'No loans found.',
        'booking.modal.addStudio': 'Add New Studio',
        'booking.modal.addEquipment': 'Add New Equipment',
        'booking.modal.book': 'Book',
        'booking.modal.request': 'Request',
        'booking.modal.edit': 'Edit',
        'booking.label.name': 'Name',
        'booking.label.capacity': 'Capacity',
        'booking.label.list': 'Equipment List (comma separated)',
        'booking.label.category': 'Category',
        'booking.label.quantity': 'Total Quantity',
        'booking.label.date': 'Date',
        'booking.label.time': 'Time',
        'booking.label.duration': 'Duration (Hours)',
        'booking.label.returnDate': 'Return Date',
        'booking.label.loanQty': 'Quantity',
        'booking.alert.stock': 'Not enough stock available!',
        'booking.alert.reduce': 'Cannot reduce total quantity below currently loaned amount.',
        'booking.info.max': 'Max available',
        'booking.info.current': 'Currently Available',
        'booking.cat.mic': 'Microphone',
        'booking.cat.inst': 'Instrument',
        'booking.cat.cable': 'Cable',
        'booking.cat.interface': 'Interface',
        'booking.cat.other': 'Other',
        'profile.title': 'My Account',
        'profile.subtitle': 'Manage your profile settings and preferences',
        'profile.toggleTheme': 'Toggle Theme',
        'profile.theme': 'Theme',
        'profile.changeAvatar': 'Change Avatar',
        'profile.appearance': 'Appearance',
        'profile.accessibility': 'Accessibility',
        'profile.fontSize': 'Font Size',
        'profile.colorProfile': 'Color Profile',
        'profile.cp.standard': 'Standard',
        'profile.cp.protanopia': 'Red-Blind (Protanopia)',
        'profile.cp.deuteranopia': 'Green-Blind (Deuteranopia)',
        'profile.cp.tritanopia': 'Blue-Blind (Tritanopia)',
        'profile.personalInfo': 'Personal Information',
        'profile.fullName': 'Full Name',
        'profile.username': 'Username',
        'profile.cohort': 'Cohort',
        'profile.department': 'Department',
        'profile.officeRoom': 'Office Room',
        'profile.accountSettings': 'Account Settings',
        'profile.notifications': 'Notifications',
        'profile.inAppEnabled': 'In-app enabled',
        'profile.configure': 'Configure',
        'profile.language': 'Language',
        'profile.chooseAvatar': 'Choose Your Avatar',
        'profile.avatar.cat': 'Cat',
        'profile.avatar.dog': 'Dog',
        'profile.avatar.duck': 'Duck',
        'profile.avatar.frog': 'Frog',
        'profile.avatar.llama': 'Llama',
        'profile.avatar.octopus': 'Octopus',
        'profile.avatar.panda': 'Panda',
        'profile.avatar.parrot': 'Parrot',
        'profile.avatar.penguin': 'Penguin',
        'profile.theme.light': 'Light',
        'profile.theme.dark': 'Dark',
        'profile.theme.contrast': 'Contrast',
        'teacher.dashboard.title': 'Teacher Dashboard',
        'teacher.dashboard.subtitle': 'Welcome back. Here is your academic overview.',
        'teacher.dashboard.newProject': 'New Project',
        'teacher.dashboard.activeStudents': 'Active Students',
        'teacher.dashboard.enrolledCohorts': 'Enrolled across cohorts',
        'teacher.dashboard.activeProjects': 'Active Projects',
        'teacher.dashboard.publishedLive': 'Published & Live',
        'teacher.dashboard.needsMarking': 'Needs Marking',
        'teacher.dashboard.submissionsReview': 'Submissions awaiting review',
        'teacher.dashboard.qa.manageStudents': 'Manage Students',
        'teacher.dashboard.qa.viewProfiles': 'View & Edit Profiles',
        'teacher.dashboard.qa.curriculum': 'Curriculum',
        'teacher.dashboard.qa.manageProjects': 'Manage Projects',
        'teacher.dashboard.qa.assessmentHub': 'Assessment Hub',
        'teacher.dashboard.qa.pending': 'Pending',
        'teacher.dashboard.qa.courses': 'Courses',
        'teacher.dashboard.qa.manageContent': 'Manage Content',
        'teacher.dashboard.qa.academicConfig': 'Academic Config',
        'teacher.dashboard.quickActions': 'Quick Actions',
        'teacher.dashboard.termProgress': 'Term Progress',
        'teacher.dashboard.markingBacklog': 'Marking Backlog',
        'teacher.dashboard.backlogMessage': 'You have high volume of unmarked work.',
        'teacher.dashboard.goToGrading': 'Go to Grading',
        'teacher.students.title': 'Manage Students',
        'teacher.students.subtitle': 'Overview of all student cohorts and performance',
        'teacher.students.addStudent': 'Add Student',
        'teacher.students.totalStudents': 'Total Students',
        'teacher.students.active': 'Active',
        'teacher.students.atRisk': 'At Risk',
        'teacher.students.searchPlaceholder': 'Search by name or username...',
        'teacher.students.allCohorts': 'All Cohorts',
        'teacher.students.level2': 'Level 2',
        'teacher.students.level3a': 'Level 3A (Year 1)',
        'teacher.students.level3b': 'Level 3B (Year 2)',
        'teacher.students.table.name': 'Name',
        'teacher.students.table.cohort': 'Cohort',
        'teacher.students.table.status': 'Status',
        'teacher.students.table.actions': 'Actions',
        'teacher.students.actions.placeholder': 'Actions...',
        'teacher.students.actions.edit': 'Edit Details',
        'teacher.students.actions.viewCreds': 'View Credentials',
        'teacher.students.actions.resetPass': 'Reset Password',
        'teacher.students.actions.delete': 'Delete Student',
        'teacher.students.noStudents': 'No students found matching your filters.',
        'teacher.students.modal.edit': 'Edit Student',
        'teacher.students.modal.add': 'Add New Student',
        'teacher.students.modal.name': 'Student Name',
        'teacher.students.modal.namePlaceholder': 'e.g. John Doe',
        'teacher.students.modal.cohort': 'Cohort',
        'teacher.students.modal.credentials': 'Credentials',
        'teacher.students.modal.username': 'Username',
        'teacher.students.modal.usernamePlaceholder': 'auto.generated',
        'teacher.students.modal.password': 'Password',
        'teacher.students.modal.passwordPlaceholder': 'Password',
        'teacher.students.modal.cancel': 'Cancel',
        'teacher.students.modal.update': 'Update Student',
        'teacher.students.modal.create': 'Create Student',
        'teacher.students.alert.fillAll': 'Please fill in all fields',
        'teacher.students.alert.updated': 'Updated Student:',
        'teacher.students.alert.created': 'Created Student:',
        'teacher.students.alert.username': 'Username:',
        'teacher.students.alert.password': 'Password:',
        'teacher.students.alert.resetConfirm': 'Reset password for',
        'teacher.students.alert.resetSuccess': 'Password reset to:',
        'teacher.students.alert.deleteConfirm': 'Are you sure you want to delete {name}? This cannot be undone.',
        'teacher.projects.title': 'Project Management',
        'teacher.projects.subtitle': 'Oversee, track, and manage all published coursework',
        'teacher.projects.newIngestion': 'New Project Ingestion',
        'teacher.projects.searchPlaceholder': 'Search projects or units...',
        'teacher.projects.studentsTracking': 'Students Tracking',
        'teacher.projects.completionRate': 'Completion Rate',
        'teacher.projects.tasksCount': 'Tasks: {count}',
        'teacher.projects.editProject': 'Edit Project',
        'teacher.projects.cohort': 'Cohort',
        'teacher.projects.noProjects': 'No projects found',
        'teacher.projects.noProjectsDesc': 'Try adjusting your filters or ingest a new project brief.',
        'teacher.projects.deleteConfirm': 'Are you sure you want to delete "{title}"? This cannot be undone.',
        'teacher.projects.overlay.settings': 'Project Settings',
        'teacher.projects.overlay.tasks': 'Tasks ({count})',
        'teacher.projects.overlay.title': 'Project Title',
        'teacher.projects.overlay.unit': 'Unit / Qualification',
        'teacher.projects.overlay.targetCohort': 'Target Cohort',
        'teacher.projects.overlay.deadline': 'Project Deadline',
        'teacher.projects.overlay.gradingScheme': 'Grading Scheme',
        'teacher.projects.overlay.xpReward': 'Completion XP Reward',
        'teacher.projects.overlay.dowdBucks': 'Completion DowdBucks',
        'teacher.projects.overlay.taskTitle': 'Task Title',
        'teacher.projects.overlay.description': 'Description',
        'teacher.projects.overlay.evidenceTypes': 'Allowed Evidence Types (Select all that apply)',
        'teacher.projects.overlay.criteria': 'Criteria References',
        'teacher.projects.overlay.addTask': 'Add Task',
        'teacher.projects.overlay.save': 'Save Changes',
        'teacher.projects.overlay.cancel': 'Cancel',
        'teacher.projects.overlay.done': 'Done',
        'teacher.projects.overlay.removeTaskConfirm': 'Are you sure you want to remove this task?',
        'teacher.projects.tracker.tracking': 'Tracking {count} Students',
        'teacher.projects.tracker.search': 'Search students...',
        'teacher.projects.tracker.status': 'Task Completion Status',
        'teacher.projects.tracker.note': 'Note',
        'teacher.projects.tracker.addNote': 'Add Note',
        'teacher.projects.tracker.completed': 'COMPLETED',
        'teacher.projects.tracker.undo': 'Undo Verification',
        'teacher.projects.tracker.verify': 'Verify Submission',
        'teacher.projects.tracker.markComplete': 'Mark Complete',
        'teacher.projects.tracker.enterNotes': 'Enter notes for this task...',
        'teacher.projects.tracker.saveNote': 'Save Note',
        'teacher.projects.tracker.selectStudent': 'Select a student from the list to view their progress.',
        'teacher.projects.tracker.uncheckConfirm': 'Are you sure you want to uncheck this task? XP will be deducted.',
        'teacher.projects.evidence.audio': 'Audio File',
        'teacher.projects.evidence.video': 'Video File',
        'teacher.projects.evidence.google': 'Google App',
        'teacher.projects.evidence.url': 'External URL',
        'teacher.quizzes.title': 'Content Management',
        'teacher.quizzes.subtitle': 'Manage your courses, lessons, and quizzes',
        'teacher.quizzes.newCourse': 'New Course',
        'teacher.quizzes.courseDesc': 'Course description...',
        'teacher.quizzes.deleteConfirm': 'Delete this course? All content inside will be moved to "Uncategorized".',
        'teacher.quizzes.enterTopic': 'Enter a topic for the quiz:',
        'teacher.quizzes.generateFail': 'Failed to generate quiz.',
        'teacher.quizzes.newQuiz': 'New Quiz',
        'teacher.quizzes.quizDesc': 'Quiz description...',
        'teacher.quizzes.newQuestion': 'New Question',
        'teacher.quizzes.option': 'Option {number}',
        'teacher.quizzes.newLesson': 'New Lesson',
        'teacher.quizzes.lessonDesc': 'Short description of the lesson...',
        'teacher.quizzes.lessonContent': '# Lesson Title\n\nEnter your lesson content here. Supports Markdown.',
        'teacher.quizzes.editCourse': 'Edit Course',
        'teacher.quizzes.createCourse': 'Create Course',
        'teacher.quizzes.field.title': 'Title',
        'teacher.quizzes.field.description': 'Description',
        'teacher.quizzes.field.color': 'Colour Theme',
        'teacher.quizzes.field.xp': 'XP Reward',
        'teacher.quizzes.field.content': 'Content (Markdown)',
        'teacher.quizzes.field.status': 'Status',
        'teacher.quizzes.field.questionType': 'Question Type',
        'teacher.quizzes.saveCourse': 'Save Course',
        'teacher.quizzes.saveLesson': 'Save Lesson',
        'teacher.quizzes.saveQuiz': 'Save Quiz',
        'teacher.quizzes.cancel': 'Cancel',
        'teacher.quizzes.settings': 'Settings',
        'teacher.quizzes.draft': 'Draft',
        'teacher.quizzes.published': 'Published',
        'teacher.quizzes.questions': 'Questions ({count})',
        'teacher.quizzes.question': 'Question {number}',
        'teacher.quizzes.enterQuestion': 'Enter question text...',
        'teacher.quizzes.type.mc': 'Multiple Choice',
        'teacher.quizzes.type.listening': 'Listening (Interval)',
        'teacher.quizzes.type.instrument': 'Instrument (Fretboard)',
        'teacher.quizzes.addOption': '+ Add Option',
        'teacher.quizzes.addQuestion': 'Add Question',
        'teacher.quizzes.backToCourses': 'Back to Courses',
        'teacher.quizzes.aiGenerate': 'AI Generate',
        'teacher.quizzes.addLesson': 'Add Lesson',
        'teacher.quizzes.createQuiz': 'Create Quiz',
        'teacher.quizzes.noContent': 'No content in this course yet.',
        'teacher.quizzes.uncategorized': 'Uncategorised',
        'teacher.quizzes.uncategorizedDesc': 'Quizzes not in any course',
        'teacher.quizzes.quizCount': '{count} Quizzes',
        'teacher.quizzes.lessonCount': '{count} Lessons',
        'teacher.ingestion.title': 'Curriculum Ingestion',
        'teacher.ingestion.subtitle': 'Convert PDF project briefs into structured coursework',
        'teacher.ingestion.publishConfirm': 'Are you sure you want to Finalise & Publish this project?\n\nIt will become immediately visible to students in the {cohort} cohort.',
        'teacher.ingestion.selected': 'selected',
        'teacher.ingestion.untitled': 'Untitled Project',
        'teacher.ingestion.unknownUnit': 'Unknown Unit',
        'teacher.ingestion.finalize': 'Finalise & Publish',
        'teacher.ingestion.reviewRequired': 'Review Required',
        'teacher.ingestion.reviewDesc': 'Please verify all extracted data below. Ensure Project Number and Name (* marked) are correct before publishing.',
        'teacher.ingestion.processing': 'Processing Brief...',
        'teacher.ingestion.upload': 'Upload Project Brief',
        'teacher.ingestion.uploadDesc': 'Select a PDF file to automatically extract tasks, deadlines, and units.',
        'teacher.ingestion.projectDetails': 'Project Details',
        'teacher.ingestion.projectTitle': 'Project Title',
        'teacher.ingestion.targetCohort': 'Target Cohort',
        'teacher.ingestion.unitsCovered': 'Units Covered',
        'teacher.ingestion.deadline': 'Project Deadline',
        'teacher.ingestion.gradingScheme': 'Grading Scheme',
        'teacher.ingestion.tasks': 'Project Tasks ({count})',
        'teacher.ingestion.addTask': 'Add Task',
        'teacher.ingestion.newTask': 'New Task',
        'teacher.ingestion.taskDesc': 'Enter task description...',
        'teacher.ingestion.taskTitle': 'Task Title',
        'teacher.ingestion.description': 'Description',
        'teacher.ingestion.evidenceTypes': 'Required Evidence Types (Select all that apply)',
        'teacher.ingestion.audio': 'Audio File',
        'teacher.ingestion.video': 'Video File',
        'teacher.ingestion.google': 'Google App',
        'teacher.ingestion.url': 'External URL',
        'teacher.ingestion.dueDate': 'Due Date',
        'teacher.ingestion.xpReward': 'XP Reward',
        'teacher.ingestion.criteria': 'Criteria (comma separated)',
        'teacher.ingestion.parseError': 'Failed to parse PDF: {error}\n\nPlease ensure it is a valid project brief.',
        'teacher.assessment.title': 'Assessment Hub',
        'teacher.assessment.subtitle': 'Manage and grade student submissions',
        'teacher.assessment.verify': 'Verify Student Work',
        'teacher.assessment.stat.pending': 'Pending',
        'teacher.assessment.stat.late': 'Late',
        'teacher.assessment.stat.completed': 'Completed Today',
        'teacher.assessment.filter': 'Filter:',
        'teacher.assessment.filter.all': 'All',
        'teacher.assessment.filter.pending': 'Pending Mark',
        'teacher.assessment.filter.late': 'Late',
        'teacher.assessment.filter.graded': 'Graded',
        'teacher.assessment.search': 'Search students or tasks...',
        'teacher.assessment.viewGrade': 'View Grade',
        'teacher.assessment.grade': 'Grade Submission',
        'teacher.assessment.noSubmissions': 'No submissions found for the selected filter.',
    },
    es: {
        'dashboard.hello': 'Hola',
        'dashboard.ready': '¿Listo para hacer ruido? Lo estás haciendo genial.',
        'dashboard.activeProjects': 'Proyectos Activos',
        'dashboard.studioTools': 'Herramientas de Estudio',
        'dashboard.dowdBucks': 'DowdBucks',
        'dashboard.level': 'Nivel',
        'dashboard.xp': 'PE',
        'dashboard.totalXp': 'Experiencia Total',
        'dashboard.nextLevel': 'PE para el siguiente nivel',
        'dashboard.continue': 'Continuar Proyecto',
        'calendar.thisWeek': 'Esta Semana',
        'calendar.upcoming': 'Próximos Eventos',
        'calendar.today': 'Hoy',
        'calendar.noEvents': 'No hay eventos próximos',
        'sidebar.dashboard': 'Tablero',
        'sidebar.learning': 'Aprendizaje',
        'sidebar.projects': 'Proyectos',
        'sidebar.resources': 'Recursos',
        'sidebar.store': 'Tienda',
        'sidebar.inventory': 'Inventario',
        'sidebar.grades': 'Calificaciones',
        'sidebar.profile': 'Perfil',
        'sidebar.calendar': 'Calendario',
        'sidebar.support': 'Soporte',
        'sidebar.logout': 'Cerrar Sesión',
    },
    fr: {
        'dashboard.hello': 'Bonjour',
        'dashboard.ready': 'Prêt à faire du bruit ? Tu t\'en sors très bien.',
        'dashboard.activeProjects': 'Projets Actifs',
        'dashboard.studioTools': 'Outils de Studio',
        'dashboard.dowdBucks': 'DowdBucks',
        'dashboard.level': 'Niveau',
        'dashboard.xp': 'XP',
        'dashboard.totalXp': 'Expérience Totale',
        'dashboard.nextLevel': 'XP pour le niveau suivant',
        'dashboard.continue': 'Continuer le Projet',
        'calendar.thisWeek': 'Cette Semaine',
        'calendar.upcoming': 'Événements à Venir',
        'calendar.today': 'Aujourd\'hui',
        'calendar.noEvents': 'Pas d\'événements à venir',
        'sidebar.dashboard': 'Tableau de bord',
        'sidebar.learning': 'Apprentissage',
        'sidebar.projects': 'Projets',
        'sidebar.resources': 'Ressources',
        'sidebar.store': 'Boutique',
        'sidebar.inventory': 'Inventaire',
        'sidebar.grades': 'Notes',
        'sidebar.profile': 'Profil',
        'sidebar.calendar': 'Calendrier',
        'sidebar.support': 'Support',
        'sidebar.logout': 'Déconnexion',
    },
    de: {
        'dashboard.hello': 'Hallo',
        'dashboard.ready': 'Bereit, etwas Lärm zu machen? Du machst das großartig.',
        'dashboard.activeProjects': 'Aktive Projekte',
        'dashboard.studioTools': 'Studio-Tools',
        'dashboard.dowdBucks': 'DowdBucks',
        'dashboard.level': 'Stufe',
        'dashboard.xp': 'EP',
        'dashboard.totalXp': 'Gesamterfahrung',
        'dashboard.nextLevel': 'EP bis zur nächsten Stufe',
        'dashboard.continue': 'Projekt fortsetzen',
        'calendar.thisWeek': 'Diese Woche',
        'calendar.upcoming': 'Anstehende Ereignisse',
        'calendar.today': 'Heute',
        'calendar.noEvents': 'Keine anstehenden Ereignisse',
        'sidebar.dashboard': 'Dashboard',
        'sidebar.learning': 'Lernen',
        'sidebar.projects': 'Projekte',
        'sidebar.resources': 'Ressourcen',
        'sidebar.store': 'Laden',
        'sidebar.inventory': 'Inventar',
        'sidebar.grades': 'Noten',
        'sidebar.profile': 'Profil',
        'sidebar.calendar': 'Kalender',
        'sidebar.support': 'Hilfe',
        'sidebar.logout': 'Abmelden',
    }
    // Other languages fall back to English for now or can be added later
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const { user } = useUser();
    const [language, setLanguage] = useState<Language>('en-gb');

    // Sync language with UserContext
    useEffect(() => {
        if (user?.language) {
            setLanguage(user.language as Language);
        }
    }, [user?.language]);

    const t = (key: string): string => {
        const dict = dictionaries[language] || dictionaries['en'];
        return dict[key] || dictionaries['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, t, setLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
